source 'https://github.com/CocoaPods/Specs.git'

target 'ARNFetchedResultsTableView', :exclusive => true do
  pod "ARNFetchedResultsTableView", :path => "../"
  pod 'ARNFetchedResultsController'
end

target 'Tests', :exclusive => true do
  pod "ARNFetchedResultsTableView", :path => "../"
  pod 'ARNFetchedResultsController'

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
